name = "ffidji"
description = "FFIDJI documentation."
license = "MIT"
homepage = "https://dr-dotnet.github.io/"
min_version = "0.13.0"

[extra]

[author]
name = "Ogxd"
homepage = "https://github.com/ogxd"

[original]
author =  "h-enk"
homepage = "https://getdoks.org/"
repo = "https://github.com/h-enk/doks"
