name: 'Build & Test'

on:
  push:
    branches:
      - '**'

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable

      - name: Install Dotnet SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'
          
      - name: Install Dependencies
        working-directory: src
        run: dotnet restore

      - name: Build
        working-directory: src
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: src
        run: dotnet test --no-restore --verbosity normal

  publish:
    needs: [build-test]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: publish
        run: echo 'publishing'