on: push
name: Deploy documentation
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: shalzz/zola-deploy-action
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: docs
          BUILD_FLAGS: --drafts
          TOKEN: ${{ secrets.DEPLOY_DOCS }}
