name: 'On Commit'

on:
  push:
    branches:
      - '**'

jobs:

  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Dotnet SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'
          
      - name: Install Dependencies
        working-directory: src
        run: dotnet restore

      - name: Build
        working-directory: src
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: src
        run: dotnet test --no-restore --verbosity normal

  push-docker:
    if: github.ref != 'refs/heads/master'
    name: Push Test Docker Image
    needs: [build-test]
    environment: dev
    runs-on: ubuntu-20.04 # Had some GLIBC 2.33 errors not found since github switched to 22.04 end of 2022
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Docker Image
        uses: ./.github/actions/push-docker
        with:
          version: '0.0.0' # A test docker image has no version
          suffix: ${{ github.ref_name }} # A test docker image can be identified by the branch name
          docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}