name: 'On Version Tag'

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  check:
    name: Check Branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

  push-docker:
    name: Push Docker
    needs: [check]
    runs-on: ubuntu-20.04 # Had some GLIBC 2.33 errors not found since github switched to 22.04 end of 2022
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Docker Image
        uses: ./.github/actions/push-docker
        with:
          version: ${{ github.ref_name }} # Since this job is triggered from x.x.x tag, we can use the tag as version
          docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
          docker-username: ${{ secrets.DOCKERHUB_USERNAME }}

  create-release:
    name: Create Release
    needs: [check]
    strategy:
      matrix:
        include:
          - target-os: 'win-x64'
            libname: 'profilers.dll'
            os: 'windows-latest'
            zip-command: '7z a -tzip'
          - target-os: 'linux-x64'
            libname: 'libprofilers.so'
            os: 'ubuntu-latest'
            zip-command: 'zip -r'
          - target-os: 'osx-arm64'
            libname: 'libprofilers.dylib'
            os: 'macos-latest'
            zip-command: 'zip -r'

    runs-on: ${{ matrix.os }}
    env:
      VERSION: ${{ github.ref_name }}
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Dotnet SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - name: Publish for ${{ matrix.target-os }}
        run: dotnet publish src/DrDotnet.Desktop/DrDotnet.Desktop.csproj -c Release --sc -r ${{ matrix.target-os }} -o pub

      - name: Copy Native Profilers
        run: cp bin/release/${{ matrix.libname }} pub/

      - name: Zip
        shell: bash
        run: (cd pub && ${{ matrix.zip-command }} ../drdotnet-${{ matrix.target-os }}.zip .)

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "drdotnet-${{ matrix.target-os }}*"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
