on:
  release:
    types: [published]

name: release

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Dotnet SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      - name: Get Version Number
        run: |
          echo "VERSION=$(head -1 CHANGELOG.md | grep -o "[0-9]\.[0-9]\.[0-9]")" >> $GITHUB_ENV
          echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
          echo Version is: $(VERSION).$(BUILD_NUMBER)

      - name: Publish for Linux
        run: dotnet publish src/DrDotnet.Desktop/DrDotnet.Desktop.csproj -c Release --self-contained true --runtime linux-x64 --output ./dist/linux

      - name: Publish for macOS
        run: dotnet publish src/DrDotnet.Desktop/DrDotnet.Desktop.csproj -c Release --self-contained true --runtime osx-x64 --output ./dist/osx

      - name: Publish for Windows
        run: dotnet publish src/DrDotnet.Desktop/DrDotnet.Desktop.csproj -c Release --self-contained true --runtime win-x64 --output ./dist/windows

      - name: Zip
        shell: bash
        run: |
          zip -r "drdotnet-windows.zip" "dist/windows"
          tar -czvf "drdotnet-linux.tar.gz" "dist/linux"
          tar -czvf "drdotnet-osx.tar.gz" "dist/osx"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "drdotnet-*"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
