name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release

    strategy:
      matrix:
        include:
          - target-os: 'win-x64'
            libname: 'profilers.dll'
            os: 'windows-latest'
            zip-command: '7z a -tzip'
          - target-os: 'linux-x64'
            libname: 'libprofilers.so'
            os: 'ubuntu-latest'
            zip-command: 'zip -r'
          - target-os: 'osx-arm64'
            libname: 'libprofilers.dylib'
            os: 'macos-latest'
            zip-command: 'zip -r'
            sign-macos: true

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Dotnet SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0

      - name: Get Version Number
        shell: bash
        run: |
          echo "VERSION=$(head -1 CHANGELOG.md | grep -o "[0-9]\.[0-9]\.[0-9]")" >> $GITHUB_ENV
          echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
          echo Version is: $(VERSION).$(BUILD_NUMBER)

      - name: Publish for ${{ matrix.target-os }}
        run: dotnet publish src/DrDotnet.Desktop/DrDotnet.Desktop.csproj -c Release --sc -r ${{ matrix.target-os }} -o pub

      - if: ${{ matrix.sign-macos }}
        name: Self-sign MacOS Certificate
        env:
          MACOS_CERTIFICATE_P12: ${{ secrets.MACOS_CERTIFICATE_P12 }}
          MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
        run: |
          echo $MACOS_CERTIFICATE_P12 | base64 --decode > certificate.p12
          security create-keychain -p actions build.keychain
          security default-keychain -s build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PASSWORD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k actions build.keychain
          rm certificate.p12
          codesign --keychain build.keychain --sign "$(security find-identity -v -p codesigning build.keychain | grep 'Self-signed Certificate' | cut -d \" -f 2)" --timestamp --options runtime --verbose --deep ./pub/DrDotnet.Desktop

      - name: Copy Native Profilers
        run: cp bin/release/${{ matrix.libname }} pub/

      - name: Zip
        shell: bash
        run: (cd pub && ${{ matrix.zip-command }} ../drdotnet-${{ matrix.target-os }}.zip .)

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "drdotnet-${{ matrix.target-os }}*"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
